config/routes.rb
LittleBen::Application.routes.draw do
  get "home/index"

  resources :users
  resources :bills
  
  get '/login',
    :to => 'page#login',
    :as => 'login'
    
  get '/about',
    :to => 'page#about',
    :as => 'about_page'
    
  

  root :to => "page#index"

end

app/models/bill.rb
# == Schema Information
#
# Table name: bills
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  summay     :text
#  body       :text
#  sponsor_id :integer
#  vote_plus  :integer
#  vote_minus :integer
#  created_at :datetime
#  updated_at :datetime
#

class Bill < ActiveRecord::Base
	attr_accessible :title, :summay, :body, :vote_minus, :vote_plus
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  acts_as_authentic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time  
  protect_from_forgery # See ActionController::RequestForgeryProtection for details  
  
  # From authlogic  
  filter_parameter_logging :password, :password_confirmation  
  helper_method :current_user_session, :current_user  
  
  private  
  def current_user_session  
    @current_user_session ||= UserSession.find  
  end  
  
  def current_user  
    @current_user ||= current_user_session && current_user_session.user  
  end 
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  # GET /bills
  # GET /bills.xml
  def index
    @bills = Bill.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.xml
  def show
    @bill = Bill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.xml
  def new
    @bill = Bill.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    @bill = Bill.find(params[:id])
  end

  # POST /bills
  # POST /bills.xml
  def create
    @bill = Bill.new(params[:bill])

    respond_to do |format|
      if @bill.save
        format.html { redirect_to(@bill, :notice => 'Bill was successfully created.') }
        format.xml  { render :xml => @bill, :status => :created, :location => @bill }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bill.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.xml
  def update
    @bill = Bill.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to(@bill, :notice => 'Bill was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bill.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.xml
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to(bills_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end

  def login
  end

  def about 
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new  
    @user_session = UserSession.new  
  end  
  
  def create  
    @user_session = UserSession.new(params[:user_session])  
    if @user_session.save  
      flash[:notice] = "Login successful!"  
      redirect_back_or_default user_path  
    else  
      render :action => :new  
    end  
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index  
  end

  # GET /users/1
  # GET /users/1.xml
  def show  
    @user = current_user  
  end 

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
  
  private  
  def login_required  
    unless current_user  
      flash[:error] = 'You must be logged in to view this page.'  
      redirect_to new_user_session_path  
    end  
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authorization.rb
module Authorization
  
  #The current user can't access the current page.
  def unauthorized!
    redirect "/login", 303
  end
 
  #Is the current user logged in?
  def logged_in?
    session['logged_in']
    #false
  end
 
  #Method called from the login controller to authenticate the user
  def authorize(username, password)
    #Basic logic to check name and password
    if(username == "jo" && password == "jo")
      session["logged_in"] = true
    end
    session["logged_in"]
  end
  
  #Destroy the session
  def logout()
    session["logged_in"] = false
  end
 
  #Called on every application's page
  def require_administrative_privileges
    unauthorized! unless logged_in? || (request.path_info == '/login' && !logged_in?)
  end
  
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :summay %><br />
    <%= f.text_area :summay %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :sponsor_id %><br />
    <%= f.text_field :sponsor_id %>
  </div>
  <div class="field">
    <%= f.label :vote_plus %><br />
    <%= f.text_field :vote_plus %>
  </div>
  <div class="field">
    <%= f.label :vote_minus %><br />
    <%= f.text_field :vote_minus %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<h1>Listing bills</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Summay</th>
    <th>Body</th>
    <th>Sponsor</th>
    <th>Vote plus</th>
    <th>Vote minus</th>
    <th>Created at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bills.each do |bill| %>
  <tr>
    <td><%= bill.title %></td>
    <td><%= bill.summay %></td>
    <td><%= bill.body %></td>
    <td><%= bill.sponsor_id %></td>
    <td><%= bill.vote_plus %></td>
    <td><%= bill.vote_minus %></td>
    <td><%= bill.created_at %></td>
    <td><%= link_to 'Show', bill %></td>
    <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
    <td><%= link_to 'Destroy', bill, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @bill.title %>
</p>

<p>
  <b>Summay:</b>
  <%= @bill.summay %>
</p>

<p>
  <b>Body:</b>
  <%= @bill.body %>
</p>

<p>
  <b>Sponsor:</b>
  <%= @bill.sponsor_id %>
</p>

<p>
  <b>Vote plus:</b>
  <%= @bill.vote_plus %>
</p>

<p>
  <b>Vote minus:</b>
  <%= @bill.vote_minus %>
</p>

<p>
  <b>Created at:</b>
  <%= @bill.created_at %>
</p>


<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>

app/views/haml/about.haml
%h1 About  
%p  
  This is a simple application using Sinatra and HAML.  

app/views/haml/index.haml
%h1 Bootstrap starter template
%p
  Use this document as a way to quick start any new project.<br> All you get is this message and a barebones HTML document.

app/views/haml/layout.haml
!!!  
%html  
  %head
    %meta(charset="utf-8")
    %title Bootstrap, from Twitter
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    %link(rel="stylesheet" href="css/bootstrap.css") 
    %style
      body {
      padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    %link(rel="stylesheet" href="css/bootstrap-responsive.css")  
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a(class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse")
            %span(class="icon-bar")
            %span(class="icon-bar")
            %span(class="icon-bar")
          %a(class="brand" href="/")
            Little Ben
          .nav-collapse
            = partial("menu")
    .container
      =yield
    		
    %script(src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js")
    %script(src="js/bootstrap.min.js")

app/views/haml/login.haml
%h1 Login 
%form(class="form-vertical" method="post")
  .controls
    %input(type="text" name="username" class="span3" placeholder="Username") 
  .controls
    %input(type="text" name="email" class="span3" placeholder="Email address") 
  .controls
    %label(class="radio")
      %input(type="radio" name="type" value="option1" checked)
      I am a member of the public
    %label(class="radio")
      %input(type="radio" name="type" value="option2")
      I am a member of the Parliament
  .controls
    %button(type="submit" class="btn btn-large btn-primary")Sign up
    %button(type="submit" class="btn btn-large")Or log in with Twitter
    

app/views/haml/menu.haml
%ul(class="nav")
  %li{:class => ("active" if request.path_info == '/') }
    %a(href="/")
      Home
  %li{:class => ("active" if request.path_info == '/about') }
    %a(href="/about")
      About
  - if !logged_in?
    %li{:class => ("active" if request.path_info == '/login') }
      %a(href="/login")
        Login
  - else
    %li{:class => ("active" if request.path_info == '/logout') }
      %a(href="/logout")
        Logout

app/views/layouts/_menu.html.erb
<ul class='nav'>
  <li <%= if request.path_info == '/' then 'class="active"'.html_safe; end%>>
    <a href='/'>
      Home
    </a>
  </li>
  <li <%= if request.path_info == '/about' then 'class="active"'.html_safe; end%>>
    <a href='/about'>
      About
    </a>
  </li>
  <li <%= if request.path_info == '/bills' then 'class="active"'.html_safe; end%>>
    <a href='/bills'>
      List Bills
    </a>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta charset='utf-8' />
    <title>Bootstrap, from Twitter</title>
    <meta content='width=device-width, initial-scale=1.0' name='viewport' />
	<%= csrf_meta_tag %>
    <link href='css/bootstrap.css' rel='stylesheet' />
	<%= stylesheet_link_tag :all %>
    <style>
      body {
      padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href='css/bootstrap-responsive.css' rel='stylesheet' />
  </head>
  <body>
    <div class='navbar navbar-fixed-top'>
      <div class='navbar-inner'>
        <div class='container'>
          <a class='btn btn-navbar' data-target='.nav-collapse' data-toggle='collapse'>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
          </a>
          <a class='brand' href='/'>
            Little Ben
          </a>
          <div class='nav-collapse'>
        	<%= render :partial => 'layouts/menu' %>  
          </div>
        </div>
      </div>
    </div>
    <div class='container'>
    	<%= yield %>
    </div>
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'></script>
    <script src='js/bootstrap.min.js'></script>
	<%= javascript_include_tag :defaults %>
  </body>
</html>

app/views/page/about.html.erb
<h1>About</h1>
<p>
  This is a simple application using Sinatra and HAML.
</p>

app/views/page/index.html.erb
<h1>Bootstrap starter template</h1>
<p>
  Use this document as a way to quick start any new project.<br> All you get is this message and a barebones HTML document.
</p>

app/views/user_sessions/_form.html.erb
# create the login views  
# /app/views/user_sessions/_form.html.erb  
<% form_for(@user_session, :url => user_session_path) do |form| %>  
  <%= form.error_messages %>  
  
  <p>  
    <%= form.label :login %>  
    <%= form.text_field :login %>  
  </p>  
  
  <p>  
    <%= form.label :password %>  
    <%= form.password_field :password %>  
  </p>  
  
  <%= form.submit 'Login' %>  
<% end %>
<!--
<h1>Login</h1>
<form class='form-vertical' method='post'>
  <div class='controls'>
    <input class='span3' name='username' placeholder='Username' type='text' />
  </div>
  <div class='controls'>
    <input class='span3' name='email' placeholder='Email address' type='text' />
  </div>
  <div class='controls'>
    <label class='radio'>
      <input checked='checked' name='type' type='radio' value='option1' />
      I am a member of the public
    </label>
    <label class='radio'>
      <input name='type' type='radio' value='option2' />
      I am a member of the Parliament
    </label>
  </div>
  <div class='controls'>
    <button class='btn btn-large btn-primary' type='submit'>Sign up</button>
    <button class='btn btn-large' type='submit'>Or log in with Twitter</button>
  </div>
</form>-->

app/views/user_sessions/new.html.erb
<% title 'Login Please' %>  
<%= render :partial => 'form' %>  

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>